name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * SAT'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Download the citations
        env:
          SCHOLARID: ${{ secrets.SCHOLARID }}
          SCOPUSID: ${{ secrets.SCOPUSID }}
          SCOPUSKEY: ${{ secrets.SCOPUSKEY }}
        run: |
          sed -i "s/<SCOPUSKEY>/$SCOPUSKEY/g" pybliometrics.cfg
          sudo mkdir -p /root/.config
          sudo cp pybliometrics.cfg /root/.config/pybliometrics.cfg
          sudo chmod -R 777 /root
          cat /root/.config/pybliometrics.cfg

          mkdir -p ~/.config
          cp pybliometrics.cfg ~/.config/pybliometrics.cfg
          cd ~
          sed -i "s|/root|$(pwd)|g" .config/pybliometrics.cfg
          cat .config/pybliometrics.cfg
          cd -

          cp config.example.yml config.yml
          sed -i "s/<SCHOLARID>/$SCHOLARID/g" config.yml
          sed -i "s/<SCOPUSID>/$SCOPUSID/g" config.yml
          sed -i "s/<SCOPUSKEY>/$SCOPUSKEY/g" config.yml
          docker compose up
      # - name: Send Message
      #   run: |
      #     export CHANGELOG="$(cat data/summ.txt)"
      #     echo "$CHANGELOG"
      #     CHANGELOG="${CHANGELOG//'%'/'%25'}"
      #     CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
      #     CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
      #     echo "::set-output name=FILE::$(echo "$CHANGELOG")"
      #   id: fileaction
      # - name: Send telegram message
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: |
      #       ${{ steps.fileaction.outputs.FILE }}
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}